
version: '2.1'

services:

    postgres_db:
      container_name: postgres_db
      image: postgres
      ports:
        - '32271:5432'
      environment:
        POSTGRES_PASSWORD: airflow
      volumes:
        - ./pgsql_data:/var/lib/postgresql/data


    airflow:
        container_name: airflow
        image: rossi619/airflow:1.0.0
        ports:
          - '8080:8080'
        links:
          - postgres_db
        restart: always
        depends_on:
            - postgres_db
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - AIRFLOW_CONN_POSTGRES_DB=postgres://postgres:airflow@postgres_db:5432/postgres
        volumes:
            - ./airflow_pipelines/dags:/usr/local/airflow/dags
            - ./airflow_pipelines/airflow.db:/usr/local/airflow/airflow.db
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3


